name: Comic - monkeyuser to ntfy
scripts:
  - script: fetch-html.js
    config:
      url: https://www.monkeyuser.com/
      outputVar: comic
      selector: .comic img
      jsonata: |
        {"url": "https://www.monkeyuser.com" & [attributes.src][0], "title": [attributes.title][0]}
  - script: jsonata.js
    config:
      expression: |
        {
          "title": data.comic.title,
          "message": data.comic.title,
          "attach": data.comic.url
        }
  - script: fetch-binary.js
  - script: ntfy.js
    config:
      url: https://ntfy.sh/jerapah-flow
triggers:
  - type: HTTP
    method: POST
    path: /new
