name: Comic - monkeyuser to ntfy
scripts:
  - script: fetch-html.js
    config:
      url: "https://www.monkeyuser.com/"
      outputVar: "httpResponse"
      selector: ".comic img"
      jsonata: |
        {"url": "https://www.monkeyuser.com" & [attributes.src][0], "title": [attributes.title][0]}
  - script: jsonata.js
    config:
      expression: |
        {"data": {"title": httpResponse.title, "message": httpResponse.title, "attach": httpResponse.url}}
  - fetch-binary.js
  - script: ntfy.js
    config:
      url: https://ntfy.sh/jerapah-flow

triggers:
  - type: HTTP
    method: POST
    path: /new
