name: cron example
description: |
  this workflow triggered by cron
scripts:
  - script: plugin/get-current-time
  - set:
      expression: '{"message": context.datetime}'
  - script: ntfy.js
    config:
      url: $VAR_ntfy_channel
      title: $DATA
triggers:
  - type: cron
    schedule: "*/20 * * * *"
