name: cron example
description: |
  this workflow triggered by cron
scripts:
  - script: ntfy.js
    config:
      url: https://ntfy.sh/jerapah-flow
triggers:
  - type: cron
    schedule: "*/20 * * * *"
