name: dev-zte-sms
description: |
  Send an SMS via a ZTE modem web UI.
  Input (data): to, message
  Password is the named secret zte_modem_password ($SECRET_).
scripts:
  - script: plugin/send-sms
    config:
      url: http://192.168.5.1/reqproc/proc_post
      password: $SECRET_sms_secret
triggers:
  - type: workflow
  - type: HTTP
    method: POST
    path: /dev-zte-sms
    auth:
      - 0f78d6d7-bd44-45d7-a826-f51c027b767f
