name: fetch-devto
scripts:
  - script: fetch-html.js
    config:
      url: https://dev.to/t/productivity/top/week
      selector: "#substories h2"
      outputVar: titles
      jsonata: "$[].text"
triggers:
  - type: HTTP
    method: POST
    path: /fetch-dev-to
