name: Jadwal Solat Jakarta ntfy
scripts:
  - id: fetch
    script: fetch-http.js
    config:
      url: https://kemenag.go.id/api/prayer-times/1301
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
  - id: transform
    script: jsonata.js
    config:
      expression: |-
        {
          "title": data.httpResponse.data.date,
          "message": "Imsak:" & data.httpResponse.data.imsak & "\n" &
                     "Subuh:" & data.httpResponse.data.subuh & "\n" &
                     "Dzuhur:" & data.httpResponse.data.dzuhur & "\n" &
                     "Ashar:" & data.httpResponse.data.ashar & "\n" &
                     "Maghrib:" & data.httpResponse.data.maghrib & "\n" &
                     "Isya:" & data.httpResponse.data.isya
        }
    needs:
      - fetch
  - id: ntfy
    script: ntfy.js
    config:
      url: $VAR_ntfy_channel
      fingerprint: true
    needs:
      - transform
  - id: slack
    script: ntfy.js
    config:
      url: $VAR_ntfy_channel2
      fingerprint: fingerprint:ntfy2
    needs:
      - transform
  - script: slack-webhook.js
    config:
      webhookUrlSecret: slack_deploy_webhook
      fingerprint: true
      fingerprintMaxAge: 1h
      text: $INPUT_message
    needs:
      - transform
triggers:
  - type: cron
    schedule: 0 5 * * *
