name: RSS - selfh.st first item to ntfy
scripts:
  - script: fetch-rss-feed.js
    config:
      url: https://selfh.st/rss/
      outputVar: item
      jsonata: items[0]
  - script: fingerprint.js
    config:
      key: selfhst-latest
      jsonata: "data.item.guid ? data.item.guid : data.item.link"
  - script: jsonata.js
    config:
      expression: |
        {
          "title": data.item.title,
          "message": data.item.contentSnippet & "\n" & data.item.link,
          "attach": data.item.mediaContent.url ? data.item.mediaContent.url : (data.item.mediaContent.$ ? data.item.mediaContent.$.url : undefined)
        }
  - script: ntfy.js
    config:
      url: https://n.0dev.web.id/system
triggers:
  - type: HTTP
    method: POST
    path: /selfhst-rss
