name: Test MinIO
scripts:
  - script: fetch-binary.js
    config:
      outputVar: file
      url: https://nsrb:error403@dav.0dev.web.id/ntfy/IyM9784UdG4S
      filename: test.png
  - script: s3.js
    config:
      action: write
      endpoint: http://localhost:9000
      bucket: default
      forcePathStyle: true
      accessKeyIdSecret: minio_user
      secretAccessKeySecret: minio_pass
      key: file.png
triggers:
  - type: HTTP
    method: POST
    path: /new
