name: jsonata
scripts:
  - get-current-time.js
  - script: jsonata.js
    config: 
      expression: '{"message": data.datetime & " " & data.processId}'
  - ntfy.js
triggers:
  - type: HTTP
    method: POST
    path: /mt

