name: jsonata
scripts:
  - plugin/get-current-time
  - script: jsonata.js
    config: 
      expression: '{"message": data.datetime & " " & data.processId}'
  - ntfy.js
triggers:
  - type: HTTP
    method: POST
    path: /mt

