name: time to ntfy example
description: |
  this workflow will send a message to ntfy with the current time
scripts:
  - script: plugin/get-current-time
    config:
      key: ""
  - script: ntfy.js
    config:
      url: https://n.0dev.web.id/system
triggers:
  - type: HTTP
    method: POST
    path: /time-to-ntfy
