name: Track Gojek Trip
scripts:
  - script: fetch-http.js
    config:
      url: https://api.gojekapi.com/live/track/491c3132c2cc7043
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        Origin: https://track.gojek.com
  - script: fingerprint.js
    config:
      key: gojek-track-status
      jsonata: data.httpResponse.status
  - script: jsonata.js
    config:
      expression: |
        {
          "data": {
            "title": httpResponse.customer_name,
            "message": httpResponse.customer_name & " : " & httpResponse.status
          }
        }
  - script: ntfy.js
    config:
      url: https://n.0dev.web.id/system
triggers:
  - type: cron
    schedule: "* * * * *"
  - type: HTTP
    method: GET
    path: /new
